[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 12
y = 12

[general]
live_config_reload = true
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]
